### ISSUE TITLE
Component/duo support, try catch?

### ISSUE THREAD

**Issue by evansolomon** [wooorm/unified#1]
Can you explain the idea behind the try/catch for a module that isn't part of the package in 3eacf6a75eaf247aa34a917906c9714d028d0871? I get that the result is that parent apps may supply their own copy of node-extend by depending on it themselves, but I can't tell why they'd want to do that. I also don't know what "component/duo support" means, and it's hard to work out what's going on just from the diff.

My use case is that I have this module in my dependency tree (via mdast) in a React Native app, and the React Native packager doesn't really love modules that cannot be resolved, so I'm trying to figure out the best way to handle this. It looks like the [node-extend](https://www.npmjs.com/package/node-extend) module is quite old and the github repo doesn't even exist anymore, so I don't particularly want to add it to my app.

Thanks.

**Comment by wooorm** [comment]
Read more about [Component](https://github.com/componentjs/component) and [Duo](http://duojs.org). Read more about installation methods for mdast in its [documentation](https://github.com/wooorm/mdast/blob/master/doc/getting-started.md).

This work-around is needed because the `extend` npm module is called `node-extend` on GitHub (the project called `node-extend` on npm is never used). GitHub is used by non-npm package managers.

I have no experience with “React Native packager”. It doesn’t yet seem to support the `browser` field, but [they seem to be working on it](https://github.com/facebook/react-native/search?q=browser+field&type=Issues).

I’m closing this because I think supporting the browser field in **react-native/packager** is the cleanest fix for this.

An alternative is the [`blacklistRE`](https://github.com/facebook/react-native/tree/master/packager#reactpackagermiddlewareoptions) found in packager

**Comment by evansolomon** [comment]
Thanks for the response. Unfortunately I don't think the blacklist option is accessible from the packager CLI. For now I fixed the issue by just adding unified v2.1.0 to the root project's dependencies.
